# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea9290baf8fa271f25a3a018cfbb52639fcb5046de71b37a8e9898623d563de7a7cac609a2f78cd83bb4efc8416728fdc65fb06212a5a0947ce1a1f45092025

test:
  secret_key_base: 0bfed2f73694e63ce8707318bc71933560f56c47810bc5732899720adb62ec481595fc0e2bcd2bb3bf5bf93f759eae2b7e98cfb72ecd17bf5b4868111bfe97c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
